"""
Clinical prompt templates for OHCA Predictor LLM module.

Provides structured templates for generating clinical decision support reports
and a PatientReportBuilder for formatting patient data into LLM-ready text.

CRITICAL SAFETY NOTICE:
All outputs from this module are EXPLANATORY SUPPORT ONLY.
They do NOT constitute medical advice, diagnosis, or treatment decisions.
Final clinical decisions must be made by qualified medical professionals.
"""

from typing import Any, Dict, List, Optional


CLINICAL_SYSTEM_PROMPT = """
You are an Emergency Medical Director AI assistant providing decision support
for cardiac arrest prediction. You are NOT a replacement for clinical judgment.

Your role is to:
1. Summarize the AI model's risk assessment in clinical context
2. Highlight key physiological findings that contribute to the risk score
3. Identify potential confounders or alternative explanations
4. Suggest clinical actions that warrant consideration
5. Flag any uncertainty in the assessment

IMPORTANT: All recommendations are advisory. Final clinical decisions must be
made by qualified medical professionals based on complete patient evaluation.

Patient Data Summary:
{patient_summary}

AI Model Assessment:
{model_assessment}

Signal Analysis:
{signal_analysis}

Please provide:
1. Clinical interpretation of the risk assessment
2. Key contributing factors
3. Potential confounders or alternative explanations
4. Recommended clinical actions
5. Areas requiring immediate attention
6. Confidence assessment of this evaluation
"""

CLINICAL_ALERT_TEMPLATE = """
## OHCA Risk Alert - Patient {patient_id}

### Risk Assessment
- OHCA Risk Score: {risk_score:.3f} ({risk_level})
- Uncertainty: {uncertainty_level}
- Time to potential event: {time_estimate}

### Key Physiological Findings
{physiological_findings}

### Contributing Factors
{contributing_factors}

### Clinical Context
{clinical_context}

### Recommended Actions
{recommended_actions}

### Confidence Assessment
{confidence_assessment}

---
*This alert was generated by AI decision support system.
All clinical decisions must be verified by qualified medical professionals.*
"""


class PatientReportBuilder:
    """Builds structured clinical reports from model output and patient data.

    This class formats raw model predictions, signal features, and patient
    demographics into structured text suitable for LLM clinical interpretation.
    """

    @staticmethod
    def build_patient_summary(patient_features: Dict[str, Any]) -> str:
        """Format patient features into a human-readable clinical summary.

        Args:
            patient_features: Dictionary containing patient demographic and
                clinical data. Expected keys include: age, sex, bmi,
                comorbidities, medications, chief_complaint, admission_diagnosis.

        Returns:
            Formatted multi-line string summarizing the patient profile.
        """
        lines: List[str] = []

        age = patient_features.get("age", "Unknown")
        sex = patient_features.get("sex", "Unknown")
        lines.append(f"Age: {age}, Sex: {sex}")

        bmi = patient_features.get("bmi")
        if bmi is not None:
            lines.append(f"BMI: {bmi:.1f} kg/m²")

        comorbidities = patient_features.get("comorbidities", [])
        if comorbidities:
            lines.append(f"Comorbidities: {', '.join(str(c) for c in comorbidities)}")
        else:
            lines.append("Comorbidities: None reported")

        medications = patient_features.get("medications", [])
        if medications:
            lines.append(f"Current Medications: {', '.join(str(m) for m in medications)}")
        else:
            lines.append("Current Medications: None reported")

        chief_complaint = patient_features.get("chief_complaint")
        if chief_complaint:
            lines.append(f"Chief Complaint: {chief_complaint}")

        admission_dx = patient_features.get("admission_diagnosis")
        if admission_dx:
            lines.append(f"Admission Diagnosis: {admission_dx}")

        medical_history = patient_features.get("medical_history", {})
        if medical_history:
            history_items = []
            for key, value in medical_history.items():
                history_items.append(f"  {key}: {value}")
            lines.append("Medical History:")
            lines.extend(history_items)

        return "\n".join(lines)

    @staticmethod
    def build_model_assessment(model_output: Dict[str, Any]) -> str:
        """Format model output into a structured clinical assessment summary.

        Args:
            model_output: Dictionary containing model prediction results.
                Expected keys: ohca_risk, survival_curve, uncertainty,
                auxiliary.

        Returns:
            Formatted string describing the model's risk assessment.
        """
        lines: List[str] = []

        ohca_risk = model_output.get("ohca_risk", 0.0)
        lines.append(f"OHCA Risk Probability: {ohca_risk:.4f} ({ohca_risk * 100:.2f}%)")

        survival_curve = model_output.get("survival_curve")
        if survival_curve is not None:
            if isinstance(survival_curve, (list, tuple)):
                lines.append(f"Survival Curve Points: {len(survival_curve)} time bins")
                if len(survival_curve) > 0:
                    lines.append(f"  Short-term survival probability: {survival_curve[0]:.4f}")
                if len(survival_curve) > 1:
                    lines.append(f"  Long-term survival probability: {survival_curve[-1]:.4f}")
            else:
                lines.append(f"Survival Curve: {survival_curve}")

        uncertainty = model_output.get("uncertainty")
        if uncertainty is not None:
            if isinstance(uncertainty, dict):
                epistemic = uncertainty.get("epistemic")
                aleatoric = uncertainty.get("aleatoric")
                total = uncertainty.get("total", uncertainty.get("combined"))
                if total is not None:
                    lines.append(f"Total Uncertainty: {total:.4f}")
                if epistemic is not None:
                    lines.append(f"Epistemic Uncertainty: {epistemic:.4f}")
                if aleatoric is not None:
                    lines.append(f"Aleatoric Uncertainty: {aleatoric:.4f}")
            else:
                lines.append(f"Uncertainty Estimate: {uncertainty}")

        auxiliary = model_output.get("auxiliary", {})
        if auxiliary:
            lines.append("Auxiliary Predictions:")
            for key, value in auxiliary.items():
                if isinstance(value, float):
                    lines.append(f"  {key}: {value:.4f}")
                else:
                    lines.append(f"  {key}: {value}")

        return "\n".join(lines)

    @staticmethod
    def build_signal_analysis(signal_features: Dict[str, Any]) -> str:
        """Format signal features into a clinical signal quality report.

        Args:
            signal_features: Dictionary containing computed signal features.
                Expected keys include: hr, hrv, rhythm, motion, spo2,
                respiratory_rate, st_segment, qt_interval, signal_quality.

        Returns:
            Formatted string summarizing signal-derived clinical features.
        """
        lines: List[str] = []

        hr = signal_features.get("hr")
        if hr is not None:
            if isinstance(hr, dict):
                mean_hr = hr.get("mean", hr.get("heart_rate"))
                if mean_hr is not None:
                    lines.append(f"Heart Rate: {mean_hr:.1f} bpm")
                hr_range = hr.get("range")
                if hr_range is not None:
                    lines.append(f"  Range: {hr_range[0]:.1f} - {hr_range[1]:.1f} bpm")
            else:
                lines.append(f"Heart Rate: {hr:.1f} bpm")

        hrv = signal_features.get("hrv", {})
        if hrv:
            lines.append("Heart Rate Variability:")
            rmssd = hrv.get("rmssd")
            if rmssd is not None:
                lines.append(f"  RMSSD: {rmssd:.2f} ms")
            sdnn = hrv.get("sdnn")
            if sdnn is not None:
                lines.append(f"  SDNN: {sdnn:.2f} ms")
            lf_hf = hrv.get("lf_hf_ratio")
            if lf_hf is not None:
                lines.append(f"  LF/HF Ratio: {lf_hf:.2f}")

        rhythm = signal_features.get("rhythm", {})
        if rhythm:
            rhythm_type = rhythm.get("classification", rhythm.get("type"))
            if rhythm_type is not None:
                lines.append(f"Rhythm: {rhythm_type}")
            ectopy = rhythm.get("ectopy_burden")
            if ectopy is not None:
                lines.append(f"  Ectopy Burden: {ectopy:.2%}")

        spo2 = signal_features.get("spo2")
        if spo2 is not None:
            if isinstance(spo2, dict):
                mean_spo2 = spo2.get("mean")
                if mean_spo2 is not None:
                    lines.append(f"SpO2: {mean_spo2:.1f}%")
                spo2_var = spo2.get("variability")
                if spo2_var is not None:
                    lines.append(f"  SpO2 Variability: {spo2_var:.2f}%")
            else:
                lines.append(f"SpO2: {spo2:.1f}%")

        resp_rate = signal_features.get("respiratory_rate")
        if resp_rate is not None:
            if isinstance(resp_rate, dict):
                mean_rr = resp_rate.get("mean", resp_rate.get("rate"))
                if mean_rr is not None:
                    lines.append(f"Respiratory Rate: {mean_rr:.1f} breaths/min")
            else:
                lines.append(f"Respiratory Rate: {resp_rate:.1f} breaths/min")

        st_segment = signal_features.get("st_segment")
        if st_segment:
            lines.append("ST Segment Analysis:")
            deviation = st_segment.get("mean_deviation")
            if deviation is not None:
                lines.append(f"  Mean Deviation: {deviation:.3f} mV")
            leads = st_segment.get("lead_deviations")
            if leads:
                for lead, dev in leads.items():
                    lines.append(f"  {lead}: {dev:.3f} mV")

        qt_interval = signal_features.get("qt_interval")
        if qt_interval:
            lines.append("QT Interval Analysis:")
            qt = qt_interval.get("qt")
            if qt is not None:
                lines.append(f"  QT: {qt:.0f} ms")
            qtc = qt_interval.get("qtc")
            if qtc is not None:
                lines.append(f"  QTc (Bazett): {qtc:.0f} ms")

        motion = signal_features.get("motion")
        if motion:
            activity = motion.get("classification")
            if activity is not None:
                lines.append(f"Activity: {activity}")
            peak_accel = motion.get("peak_acceleration")
            if peak_accel is not None:
                lines.append(f"  Peak Acceleration: {peak_accel:.2f} g")

        signal_quality = signal_features.get("signal_quality")
        if signal_quality:
            lines.append("Signal Quality:")
            if isinstance(signal_quality, dict):
                for modality, quality in signal_quality.items():
                    if isinstance(quality, (int, float)):
                        lines.append(f"  {modality}: {quality:.2f}")
                    else:
                        lines.append(f"  {modality}: {quality}")
            else:
                lines.append(f"  Overall: {signal_quality}")

        return "\n".join(lines)

    @staticmethod
    def format_alert(
        patient_id: str,
        risk_score: float,
        model_output: Dict[str, Any],
        patient_features: Dict[str, Any],
        signal_features: Dict[str, Any],
    ) -> str:
        """Format a complete clinical alert from all available data.

        Args:
            patient_id: Unique patient identifier.
            risk_score: OHCA risk probability score in [0, 1].
            model_output: Full model output dictionary.
            patient_features: Patient demographic and clinical features.
            signal_features: Computed signal analysis features.

        Returns:
            Formatted clinical alert string ready for LLM consumption.
        """
        builder = PatientReportBuilder()

        risk_level = builder.determine_risk_level(risk_score)

        uncertainty = model_output.get("uncertainty", {})
        if isinstance(uncertainty, dict):
            uncertainty_value = uncertainty.get("total", uncertainty.get("combined", 0.0))
        else:
            uncertainty_value = float(uncertainty) if uncertainty else 0.0
        uncertainty_level = builder.determine_uncertainty_level(uncertainty_value)

        time_estimate = _estimate_time_to_event(risk_score, model_output)

        physiological_findings = builder.build_signal_analysis(signal_features)

        contributing_factors = _identify_contributing_factors(
            patient_features, signal_features, model_output
        )

        clinical_context = builder.build_patient_summary(patient_features)

        recommended_actions = _generate_recommended_actions(
            risk_score, risk_level, signal_features, patient_features
        )

        confidence_assessment = _assess_confidence(
            uncertainty_level, signal_features, model_output
        )

        return CLINICAL_ALERT_TEMPLATE.format(
            patient_id=patient_id,
            risk_score=risk_score,
            risk_level=risk_level,
            uncertainty_level=uncertainty_level,
            time_estimate=time_estimate,
            physiological_findings=physiological_findings,
            contributing_factors=contributing_factors,
            clinical_context=clinical_context,
            recommended_actions=recommended_actions,
            confidence_assessment=confidence_assessment,
        )

    @staticmethod
    def determine_risk_level(risk_score: float) -> str:
        """Map a continuous risk score to a categorical risk level.

        Args:
            risk_score: OHCA risk probability in [0, 1].

        Returns:
            One of: "LOW", "MODERATE", "HIGH", "CRITICAL".
        """
        if risk_score < 0.10:
            return "LOW"
        elif risk_score < 0.25:
            return "MODERATE"
        elif risk_score < 0.50:
            return "HIGH"
        else:
            return "CRITICAL"

    @staticmethod
    def determine_uncertainty_level(uncertainty: float) -> str:
        """Map a continuous uncertainty estimate to a categorical level.

        Args:
            uncertainty: Uncertainty value, typically in [0, 1].

        Returns:
            One of: "LOW", "MODERATE", "HIGH".
        """
        if uncertainty < 0.10:
            return "LOW"
        elif uncertainty < 0.25:
            return "MODERATE"
        else:
            return "HIGH"


def _estimate_time_to_event(
    risk_score: float, model_output: Dict[str, Any]
) -> str:
    """Estimate time-to-event from survival curve or risk score.

    Args:
        risk_score: OHCA risk probability.
        model_output: Model output dictionary potentially containing
            survival_curve data.

    Returns:
        Human-readable string estimating time to potential event.
    """
    survival_curve = model_output.get("survival_curve")
    if survival_curve is not None and isinstance(survival_curve, (list, tuple)):
        if len(survival_curve) >= 2:
            for idx, survival_prob in enumerate(survival_curve):
                if survival_prob < 0.5:
                    hours_per_bin = 4.0
                    estimated_hours = idx * hours_per_bin
                    if estimated_hours <= 1:
                        return f"< 1 hour (survival drops below 50% at bin {idx})"
                    elif estimated_hours < 24:
                        return f"~{estimated_hours:.0f} hours (survival drops below 50% at bin {idx})"
                    else:
                        days = estimated_hours / 24
                        return f"~{days:.1f} days (survival drops below 50% at bin {idx})"
            return "> 48 hours (survival remains above 50%)"

    if risk_score >= 0.50:
        return "< 2 hours (high risk - immediate attention recommended)"
    elif risk_score >= 0.25:
        return "2-6 hours (elevated risk - close monitoring recommended)"
    elif risk_score >= 0.10:
        return "6-12 hours (moderate risk - continued monitoring)"
    else:
        return "> 12 hours (low risk - routine monitoring)"


def _identify_contributing_factors(
    patient_features: Dict[str, Any],
    signal_features: Dict[str, Any],
    model_output: Dict[str, Any],
) -> str:
    """Identify key contributing factors to the risk assessment.

    Args:
        patient_features: Patient demographic and clinical data.
        signal_features: Computed signal features.
        model_output: Model output dictionary.

    Returns:
        Formatted string listing contributing factors.
    """
    factors: List[str] = []

    hr = signal_features.get("hr")
    if hr is not None:
        hr_value = hr.get("mean", hr) if isinstance(hr, dict) else hr
        if isinstance(hr_value, (int, float)):
            if hr_value < 50:
                factors.append("- Bradycardia detected (HR < 50 bpm)")
            elif hr_value > 120:
                factors.append("- Tachycardia detected (HR > 120 bpm)")

    hrv = signal_features.get("hrv", {})
    rmssd = hrv.get("rmssd")
    if rmssd is not None and isinstance(rmssd, (int, float)):
        if rmssd < 20:
            factors.append("- Very low HRV (RMSSD < 20 ms) - reduced autonomic variability")
        elif rmssd < 30:
            factors.append("- Low HRV (RMSSD < 30 ms) - reduced autonomic variability")

    lf_hf = hrv.get("lf_hf_ratio")
    if lf_hf is not None and isinstance(lf_hf, (int, float)):
        if lf_hf > 3.0:
            factors.append("- Elevated LF/HF ratio (>3.0) - sympathetic dominance")
        elif lf_hf < 0.5:
            factors.append("- Low LF/HF ratio (<0.5) - parasympathetic dominance")

    spo2 = signal_features.get("spo2")
    if spo2 is not None:
        spo2_value = spo2.get("mean", spo2) if isinstance(spo2, dict) else spo2
        if isinstance(spo2_value, (int, float)) and spo2_value < 92:
            factors.append(f"- Hypoxemia detected (SpO2 {spo2_value:.1f}%)")

    st_segment = signal_features.get("st_segment", {})
    st_deviation = st_segment.get("mean_deviation")
    if st_deviation is not None and isinstance(st_deviation, (int, float)):
        if abs(st_deviation) > 0.1:
            factors.append(
                f"- ST segment deviation ({st_deviation:+.3f} mV) - "
                "possible ischemic changes"
            )

    qt_interval = signal_features.get("qt_interval", {})
    qtc = qt_interval.get("qtc")
    if qtc is not None and isinstance(qtc, (int, float)):
        if qtc > 500:
            factors.append(f"- Prolonged QTc ({qtc:.0f} ms) - elevated arrhythmia risk")
        elif qtc > 470:
            factors.append(f"- Borderline QTc ({qtc:.0f} ms) - monitor for QT prolongation")

    rhythm = signal_features.get("rhythm", {})
    ectopy = rhythm.get("ectopy_burden")
    if ectopy is not None and isinstance(ectopy, (int, float)):
        if ectopy > 0.10:
            factors.append(f"- High ectopy burden ({ectopy:.1%}) - frequent ectopic beats")
        elif ectopy > 0.05:
            factors.append(f"- Moderate ectopy burden ({ectopy:.1%}) - ectopic activity present")

    rhythm_type = rhythm.get("classification", rhythm.get("type"))
    if rhythm_type is not None and rhythm_type not in ("sinus", "normal sinus"):
        factors.append(f"- Abnormal rhythm: {rhythm_type}")

    age = patient_features.get("age")
    if age is not None and isinstance(age, (int, float)):
        if age > 75:
            factors.append(f"- Advanced age ({age} years) - elevated baseline risk")

    comorbidities = patient_features.get("comorbidities", [])
    if comorbidities:
        cardiac_comorbidities = [
            c for c in comorbidities
            if any(
                keyword in str(c).lower()
                for keyword in ["cardiac", "heart", "chf", "cad", "mi", "arrhythmia"]
            )
        ]
        if cardiac_comorbidities:
            factors.append(
                f"- Cardiac comorbidities: {', '.join(str(c) for c in cardiac_comorbidities)}"
            )

    resp_rate = signal_features.get("respiratory_rate")
    if resp_rate is not None:
        rr_value = resp_rate.get("mean", resp_rate) if isinstance(resp_rate, dict) else resp_rate
        if isinstance(rr_value, (int, float)):
            if rr_value > 24:
                factors.append(f"- Tachypnea detected (RR {rr_value:.0f} breaths/min)")
            elif rr_value < 10:
                factors.append(f"- Bradypnea detected (RR {rr_value:.0f} breaths/min)")

    if not factors:
        factors.append("- No significant contributing factors identified from available data")

    return "\n".join(factors)


def _generate_recommended_actions(
    risk_score: float,
    risk_level: str,
    signal_features: Dict[str, Any],
    patient_features: Dict[str, Any],
) -> str:
    """Generate recommended clinical actions based on risk assessment.

    Args:
        risk_score: OHCA risk probability.
        risk_level: Categorical risk level string.
        signal_features: Computed signal features.
        patient_features: Patient data.

    Returns:
        Formatted string of recommended clinical actions.
    """
    actions: List[str] = []

    if risk_level == "CRITICAL":
        actions.append("1. IMMEDIATE: Initiate continuous cardiac monitoring")
        actions.append("2. IMMEDIATE: Ensure defibrillator is immediately available")
        actions.append("3. IMMEDIATE: Notify attending physician of critical risk")
        actions.append("4. Prepare for potential resuscitation")
        actions.append("5. Establish IV access if not already present")
        actions.append("6. Obtain stat 12-lead ECG")
        actions.append("7. Consider transfer to higher acuity setting")
    elif risk_level == "HIGH":
        actions.append("1. Initiate continuous cardiac monitoring")
        actions.append("2. Ensure defibrillator within reach")
        actions.append("3. Notify clinical team of elevated risk")
        actions.append("4. Obtain 12-lead ECG and compare with prior")
        actions.append("5. Review current medications for pro-arrhythmic risk")
        actions.append("6. Consider telemetry admission")
    elif risk_level == "MODERATE":
        actions.append("1. Increase monitoring frequency")
        actions.append("2. Document current vital signs for trending")
        actions.append("3. Review recent labs (electrolytes, troponin)")
        actions.append("4. Assess clinical trajectory and response to treatment")
        actions.append("5. Consider repeat assessment in 2-4 hours")
    else:
        actions.append("1. Continue routine monitoring per protocol")
        actions.append("2. Document risk assessment in patient chart")
        actions.append("3. Reassess if clinical status changes")
        actions.append("4. Standard nursing observations")

    hrv = signal_features.get("hrv", {})
    rmssd = hrv.get("rmssd")
    if rmssd is not None and isinstance(rmssd, (int, float)) and rmssd < 20:
        actions.append("7. Consider HRV-guided autonomic assessment")

    spo2 = signal_features.get("spo2")
    if spo2 is not None:
        spo2_val = spo2.get("mean", spo2) if isinstance(spo2, dict) else spo2
        if isinstance(spo2_val, (int, float)) and spo2_val < 92:
            actions.append("8. Evaluate oxygenation and consider supplemental O2")

    st_segment = signal_features.get("st_segment", {})
    st_dev = st_segment.get("mean_deviation")
    if st_dev is not None and isinstance(st_dev, (int, float)) and abs(st_dev) > 0.1:
        actions.append("9. Evaluate for acute ischemia - consider cardiology consult")

    return "\n".join(actions)


def _assess_confidence(
    uncertainty_level: str,
    signal_features: Dict[str, Any],
    model_output: Dict[str, Any],
) -> str:
    """Generate a confidence assessment for the evaluation.

    Args:
        uncertainty_level: Categorical uncertainty level.
        signal_features: Computed signal features.
        model_output: Model output dictionary.

    Returns:
        Formatted confidence assessment string.
    """
    lines: List[str] = []

    if uncertainty_level == "LOW":
        lines.append("Model confidence: HIGH")
        lines.append("The model's prediction has low uncertainty, suggesting")
        lines.append("consistent patterns across the ensemble or MC dropout samples.")
    elif uncertainty_level == "MODERATE":
        lines.append("Model confidence: MODERATE")
        lines.append("The model shows moderate uncertainty. Clinical correlation")
        lines.append("is particularly important for this assessment.")
    else:
        lines.append("Model confidence: LOW")
        lines.append("The model's prediction has HIGH uncertainty. This assessment")
        lines.append("should be interpreted with significant caution. Additional")
        lines.append("clinical data or alternative diagnostic approaches may be needed.")

    signal_quality = signal_features.get("signal_quality")
    if signal_quality is not None:
        if isinstance(signal_quality, dict):
            low_quality = [
                modality
                for modality, quality in signal_quality.items()
                if isinstance(quality, (int, float)) and quality < 0.5
            ]
            if low_quality:
                lines.append(
                    f"\nSignal quality concerns for: {', '.join(low_quality)}"
                )
                lines.append(
                    "Low signal quality may reduce prediction reliability."
                )
        elif isinstance(signal_quality, (int, float)) and signal_quality < 0.5:
            lines.append(
                "\nOverall signal quality is below optimal threshold."
            )
            lines.append("Prediction reliability may be reduced.")

    auxiliary = model_output.get("auxiliary", {})
    if "reconstruction_loss" in auxiliary:
        recon_loss = auxiliary["reconstruction_loss"]
        if isinstance(recon_loss, (int, float)) and recon_loss > 0.5:
            lines.append(
                "\nHigh reconstruction loss indicates the input may differ"
            )
            lines.append("significantly from training distribution (possible OOD).")

    lines.append(
        "\nDISCLAIMER: This confidence assessment is generated by an AI system"
    )
    lines.append(
        "and does not replace clinical judgment. All findings should be"
    )
    lines.append("verified through direct patient evaluation.")

    return "\n".join(lines)
