#!/usr/bin/env python3
"""Plot training curves from CSV log file generated by train_v6_watch.py."""

import os
import sys
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def plot_training_curves(csv_path, out_dir):
    if not os.path.exists(csv_path):
        print(f"No training log found at {csv_path}")
        print("Re-run train_v6_watch.py to generate training logs with TensorBoard + CSV.")
        return

    df = pd.read_csv(csv_path)
    os.makedirs(out_dir, exist_ok=True)

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Loss
    ax = axes[0, 0]
    ax.plot(df["epoch"], df["loss"], label="Train Loss", color="#2c3e50", lw=2)
    ax.plot(df["epoch"], df["val_loss"], label="Val Loss", color="#e74c3c", lw=2, ls="--")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Loss"); ax.set_title("Training & Validation Loss")
    ax.legend(); ax.grid(True, alpha=0.3)

    # AUROC
    ax = axes[0, 1]
    if "auc" in df.columns:
        ax.plot(df["epoch"], df["auc"], label="Train AUC", color="#2c3e50", lw=2)
    if "val_auc" in df.columns:
        ax.plot(df["epoch"], df["val_auc"], label="Val AUC", color="#27ae60", lw=2, ls="--")
    ax.set_xlabel("Epoch"); ax.set_ylabel("AUROC"); ax.set_title("Area Under ROC Curve")
    ax.legend(); ax.grid(True, alpha=0.3)

    # Learning rate
    ax = axes[1, 0]
    if "lr" in df.columns:
        ax.plot(df["epoch"], df["lr"], color="#8e44ad", lw=2)
    ax.set_xlabel("Epoch"); ax.set_ylabel("Learning Rate"); ax.set_title("Learning Rate Schedule")
    ax.set_yscale("log"); ax.grid(True, alpha=0.3)

    # Accuracy
    ax = axes[1, 1]
    # Compute accuracy from loss or skip if not available
    ax.axis("off")
    ax.text(0.5, 0.5, "See TensorBoard for\nepoch-level metrics",
            ha="center", va="center", fontsize=14, color="gray",
            transform=ax.transAxes)

    fig.suptitle("v6-watch Training Curves", fontsize=14, y=1.01)
    fig.tight_layout()
    fig.savefig(os.path.join(out_dir, "v6_training_curves.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {out_dir}/v6_training_curves.png")

if __name__ == "__main__":
    csv_path = "production/cvd_risk_v6_watch/training_log.csv"
    out_dir = "evaluation"
    plot_training_curves(csv_path, out_dir)
