#!/usr/bin/env python3
"""Plot training curves from CSV log file generated by train_v6_watch.py or train_v7_watch.py."""

import os
import sys
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def plot_training_curves(csv_path, out_dir, version="v6"):
    if not os.path.exists(csv_path):
        print(f"No training log found at {csv_path}")
        print("Re-run training script to generate training logs with TensorBoard + CSV.")
        return

    df = pd.read_csv(csv_path)
    os.makedirs(out_dir, exist_ok=True)

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Loss
    ax = axes[0, 0]
    ax.plot(df["epoch"], df["loss"], label="Train Loss", color="#2c3e50", lw=2)
    ax.plot(df["epoch"], df["val_loss"], label="Val Loss", color="#e74c3c", lw=2, ls="--")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Loss"); ax.set_title("Training & Validation Loss")
    ax.legend(); ax.grid(True, alpha=0.3)

    # AUROC
    ax = axes[0, 1]
    if "auc" in df.columns:
        ax.plot(df["epoch"], df["auc"], label="Train AUC", color="#2c3e50", lw=2)
    if "val_auc" in df.columns:
        ax.plot(df["epoch"], df["val_auc"], label="Val AUC", color="#27ae60", lw=2, ls="--")
    ax.set_xlabel("Epoch"); ax.set_ylabel("AUROC"); ax.set_title("Area Under ROC Curve")
    ax.legend(); ax.grid(True, alpha=0.3)

    # Learning rate
    ax = axes[1, 0]
    if "lr" in df.columns:
        ax.plot(df["epoch"], df["lr"], color="#8e44ad", lw=2)
    ax.set_xlabel("Epoch"); ax.set_ylabel("Learning Rate"); ax.set_title("Learning Rate Schedule")
    ax.set_yscale("log"); ax.grid(True, alpha=0.3)

    # Precision / Recall
    ax = axes[1, 1]
    if "precision" in df.columns:
        ax.plot(df["epoch"], df["precision"], label="Train Precision", color="#2c3e50", lw=2)
    if "val_precision" in df.columns:
        ax.plot(df["epoch"], df["val_precision"], label="Val Precision", color="#f39c12", lw=2, ls="--")
    if "recall" in df.columns:
        ax.plot(df["epoch"], df["recall"], label="Train Recall", color="#3498db", lw=2)
    if "val_recall" in df.columns:
        ax.plot(df["epoch"], df["val_recall"], label="Val Recall", color="#e74c3c", lw=2, ls="--")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Score"); ax.set_title("Precision & Recall")
    ax.legend(fontsize=9); ax.grid(True, alpha=0.3)

    fig.suptitle(f"{version}-watch Training Curves", fontsize=14, y=1.01)
    fig.tight_layout()
    fig.savefig(os.path.join(out_dir, f"{version}_training_curves.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {out_dir}/{version}_training_curves.png")

if __name__ == "__main__":
    version = sys.argv[1] if len(sys.argv) > 1 else "v7"
    csv_path = f"production/cvd_risk_{version}_watch/training_log.csv"
    out_dir = "evaluation"
    plot_training_curves(csv_path, out_dir, version)
